# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/devise-bootstrap-views/all/devise-bootstrap-views.rbi
#
# devise-bootstrap-views-1.1.0

module DeviseBootstrapViewsHelper
  def bootstrap_devise_error_messages!; end
end
module DeviseBootstrapViews
end
class DeviseBootstrapViews::Engine < Rails::Engine
end
class DeviseBootstrapViews::Railtie < Rails::Railtie
  def self.pattern_from(args); end
end
