# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/google_custom_search_api/all/google_custom_search_api.rbi
#
# google_custom_search_api-2.0.0

module GoogleCustomSearchApi
  def fetch(url); end
  def search(query, opts = nil); end
  def search_and_return_all_results(query, opts = nil); end
  def url(query, opts = nil); end
  extend GoogleCustomSearchApi
end
class GoogleCustomSearchApi::ResponseData < Hash
  def deep_parse(data); end
  def initialize(data = nil); end
  def method_missing(*args); end
end
