# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/highcharts-rails/all/highcharts-rails.rbi
#
# highcharts-rails-6.0.3

module Highcharts
end
module Highcharts::Rails
end
class Highcharts::Rails::Engine < Rails::Engine
end
