# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/histogram/all/histogram.rbi
#
# histogram-0.2.4.1

class NArray
end
module Histogram
  def avg_ints(one, two); end
  def histogram(*args); end
  def number_of_bins(methd = nil, quartile_method = nil); end
  def self.iqrange(obj, opts = nil); end
  def self.median(sorted); end
  def self.minmax(obj); end
  def self.sample_stats(obj); end
end
