# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/nested_form/all/nested_form.rbi
#
# nested_form-0.3.2

module NestedForm
end
class NestedForm::Engine < Rails::Engine
end
module NestedForm::BuilderMixin
  def fields_blueprint_id_for(association); end
  def fields_for_nested_model(name, object, options, block); end
  def fields_for_with_nested_attributes(association_name, *args); end
  def link_to_add(*args, &block); end
  def link_to_remove(*args, &block); end
end
class NestedForm::Builder < ActionView::Helpers::FormBuilder
  include NestedForm::BuilderMixin
end
module NestedForm::ViewHelper
  def after_nested_form(association, &block); end
  def after_nested_form_callbacks; end
  def nested_form_for(*args, &block); end
end
