# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/open-weather/all/open-weather.rbi
#
# open-weather-0.12.0

module OpenWeather
end
class OpenWeather::Base
  def extract_options!(options); end
  def initialize(url, options); end
  def message; end
  def options; end
  def parse_response(response); end
  def retrieve(url = nil); end
  def send_request(url = nil); end
  def status; end
  def success?; end
  def url; end
  def weather_info; end
  extend OpenWeather::ClassMethods
end
class OpenWeather::Current < OpenWeather::Base
  def initialize(options = nil); end
  extend OpenWeather::SeveralCitiesClassMethods
end
module OpenWeather::ClassMethods
  def city(city, options = nil); end
  def city_id(id, options = nil); end
  def geocode(lat, lon, options = nil); end
end
module OpenWeather::SeveralCitiesClassMethods
  def circle_zone(lat, lon, count, options = nil); end
  def cities(ids, options = nil); end
  def encode_array(arr); end
  def rectangle_zone(top_left_lat, top_left_lon, bottom_right_lat, bottom_right_lon, map_zoom, options = nil); end
end
