# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/rack-pjax/all/rack-pjax.rbi
#
# rack-pjax-1.1.0

module Rack
end
class Rack::Pjax
  def call(env); end
  def container_selector(env); end
  def initialize(app); end
  def pjax?(env); end
  include Rack::Utils
end
