# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/rails_admin_charts/all/rails_admin_charts.rbi
#
# rails_admin_charts-0.0.12

module RailsAdminCharts
  def self.included(base); end
end
class RailsAdminCharts::Engine < Rails::Engine
end
module RailsAdmin
end
module RailsAdmin::Config
end
module RailsAdmin::Config::Actions
  def self.charts(&block); end
end
class RailsAdmin::Config::Actions::Charts < RailsAdmin::Config::Actions::Base
  def collection(*args, &block); end
  def collection?; end
  def http_methods(*args, &block); end
  def link_icon(*args, &block); end
  def pjax(*args, &block); end
  def pjax?; end
  def visible(*args, &block); end
end
module RailsAdminCharts::ClassMethods
  def chart_type; end
  def delta_records_since(since = nil); end
  def graph_data(since = nil); end
  def label_rotation; end
  def total_records_since(since = nil); end
  def xaxis; end
end
