# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/rails_admin_rollincode/all/rails_admin_rollincode.rbi
#
# rails_admin_rollincode-1.3

module RailsAdminRollincode
end
class RailsAdminRollincode::Engine < Rails::Engine
end
