# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/receipts/all/receipts.rbi
#
# receipts-1.0.4

module Receipts
end
class Receipts::Receipt < Prawn::Document
  def attributes; end
  def charge_details; end
  def company; end
  def custom_font; end
  def default_message; end
  def default_subheading; end
  def footer; end
  def generate; end
  def header; end
  def id; end
  def initialize(attributes); end
  def line_items; end
  def logo; end
  def message; end
  def product; end
  def setup_fonts; end
  def subheading; end
end
class Receipts::Invoice < Prawn::Document
  def attributes; end
  def bill_to; end
  def charge_details; end
  def company; end
  def custom_font; end
  def default_message; end
  def default_subheading; end
  def due_date; end
  def footer; end
  def generate; end
  def header; end
  def id; end
  def initialize(attributes); end
  def issue_date; end
  def label(text); end
  def line_items; end
  def logo; end
  def message; end
  def product; end
  def setup_fonts; end
  def status; end
  def subheading; end
end
