# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/remotipart/all/remotipart.rbi
#
# remotipart-a1860d64aef4

module Remotipart
end
module Remotipart::ViewHelper
  def remotipart_response(options = nil, &block); end
end
module Remotipart::RequestHelper
  def remotipart_requested?; end
  def remotipart_submitted?; end
end
module Remotipart::RenderOverrides
  def self.included(base); end
  def treat_render_for_remotipart(render_return_value); end
  include ActionView::Helpers::JavaScriptHelper
  include ERB::Util
end
module Remotipart::RenderOverrides::Prependable
  def render(*args, &block); end
end
module Remotipart::RenderOverrides::Includable
  def render_with_remotipart(*args, &block); end
end
class Remotipart::Middleware
  def call(env); end
  def initialize(app); end
end
module Remotipart::Rails
end
class Remotipart::Rails::Engine < Rails::Engine
end
