# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/telegram-bot-ruby/all/telegram-bot-ruby.rbi
#
# telegram-bot-ruby-0.13.0

module Telegram
end
module Telegram::Bot
  def self.configuration; end
  def self.configuration=(arg0); end
  def self.configure; end
end
module Telegram::Bot::Types
end
module Telegram::Bot::Types::Compactable
  def to_compact_hash; end
end
class Telegram::Bot::Types::Base
  def self.attribute(name, type = nil, options = nil); end
  extend Virtus::ClassMethods
  extend Virtus::Extensions::AllowedWriterMethods
  include Anonymous_Module_104
  include Anonymous_Virtus_AttributeSet_103
  include Telegram::Bot::Types::Compactable
  include Virtus::ClassInclusions::Methods
  include Virtus::InstanceMethods
  include Virtus::InstanceMethods::Constructor
  include Virtus::InstanceMethods::MassAssignment
  include Virtus::Model::Constructor
  include Virtus::Model::Core
  include Virtus::Model::MassAssignment
end
module Anonymous_Module_104
  def self.extended(object); end
  def self.included(object); end
end
module Anonymous_Virtus_AttributeSet_103
end
module Anonymous_Virtus_AttributeSet_105
  def can_join_groups; end
  def can_join_groups=(value); end
  def can_join_groups?; end
  def can_read_all_group_messages; end
  def can_read_all_group_messages=(value); end
  def can_read_all_group_messages?; end
  def first_name; end
  def first_name=(value); end
  def id; end
  def id=(value); end
  def is_bot; end
  def is_bot=(value); end
  def is_bot?; end
  def language_code; end
  def language_code=(value); end
  def last_name; end
  def last_name=(value); end
  def supports_inline_queries; end
  def supports_inline_queries=(value); end
  def supports_inline_queries?; end
  def username; end
  def username=(value); end
end
class Telegram::Bot::Types::User < Telegram::Bot::Types::Base
  include Anonymous_Virtus_AttributeSet_105
end
module Anonymous_Virtus_AttributeSet_106
  def file_id; end
  def file_id=(value); end
  def file_size; end
  def file_size=(value); end
  def file_unique_id; end
  def file_unique_id=(value); end
  def height; end
  def height=(value); end
  def width; end
  def width=(value); end
end
class Telegram::Bot::Types::PhotoSize < Telegram::Bot::Types::Base
  include Anonymous_Virtus_AttributeSet_106
end
module Anonymous_Virtus_AttributeSet_107
  def duration; end
  def duration=(value); end
  def file_id; end
  def file_id=(value); end
  def file_size; end
  def file_size=(value); end
  def file_unique_id; end
  def file_unique_id=(value); end
  def mime_type; end
  def mime_type=(value); end
  def performer; end
  def performer=(value); end
  def thumb; end
  def thumb=(value); end
  def title; end
  def title=(value); end
end
class Telegram::Bot::Types::Audio < Telegram::Bot::Types::Base
  include Anonymous_Virtus_AttributeSet_107
end
module Anonymous_Virtus_AttributeSet_108
  def file_id; end
  def file_id=(value); end
  def file_name; end
  def file_name=(value); end
  def file_size; end
  def file_size=(value); end
  def file_unique_id; end
  def file_unique_id=(value); end
  def mime_type; end
  def mime_type=(value); end
  def thumb; end
  def thumb=(value); end
end
class Telegram::Bot::Types::Document < Telegram::Bot::Types::Base
  include Anonymous_Virtus_AttributeSet_108
end
module Anonymous_Virtus_AttributeSet_109
  def point; end
  def point=(value); end
  def x_shift; end
  def x_shift=(value); end
  def y_shift; end
  def y_shift=(value); end
  def zoom; end
  def zoom=(value); end
end
class Telegram::Bot::Types::MaskPosition < Telegram::Bot::Types::Base
  include Anonymous_Virtus_AttributeSet_109
end
module Anonymous_Virtus_AttributeSet_110
  def emoji; end
  def emoji=(value); end
  def file_id; end
  def file_id=(value); end
  def file_size; end
  def file_size=(value); end
  def file_unique_id; end
  def file_unique_id=(value); end
  def height; end
  def height=(value); end
  def is_animated; end
  def is_animated=(value); end
  def is_animated?; end
  def mask_position; end
  def mask_position=(value); end
  def set_name; end
  def set_name=(value); end
  def thumb; end
  def thumb=(value); end
  def width; end
  def width=(value); end
end
class Telegram::Bot::Types::Sticker < Telegram::Bot::Types::Base
  include Anonymous_Virtus_AttributeSet_110
end
module Anonymous_Virtus_AttributeSet_111
  def contains_masks; end
  def contains_masks=(value); end
  def contains_masks?; end
  def is_animated; end
  def is_animated=(value); end
  def is_animated?; end
  def name; end
  def name=(value); end
  def stickers; end
  def stickers=(value); end
  def thumb; end
  def thumb=(value); end
  def title; end
  def title=(value); end
end
class Telegram::Bot::Types::StickerSet < Telegram::Bot::Types::Base
  include Anonymous_Virtus_AttributeSet_111
end
module Anonymous_Virtus_AttributeSet_112
  def duration; end
  def duration=(value); end
  def file_id; end
  def file_id=(value); end
  def file_size; end
  def file_size=(value); end
  def file_unique_id; end
  def file_unique_id=(value); end
  def height; end
  def height=(value); end
  def mime_type; end
  def mime_type=(value); end
  def thumb; end
  def thumb=(value); end
  def width; end
  def width=(value); end
end
class Telegram::Bot::Types::Video < Telegram::Bot::Types::Base
  include Anonymous_Virtus_AttributeSet_112
end
module Anonymous_Virtus_AttributeSet_113
  def duration; end
  def duration=(value); end
  def file_id; end
  def file_id=(value); end
  def file_size; end
  def file_size=(value); end
  def file_unique_id; end
  def file_unique_id=(value); end
  def mime_type; end
  def mime_type=(value); end
end
class Telegram::Bot::Types::Voice < Telegram::Bot::Types::Base
  include Anonymous_Virtus_AttributeSet_113
end
module Anonymous_Virtus_AttributeSet_114
  def duration; end
  def duration=(value); end
  def file_id; end
  def file_id=(value); end
  def file_size; end
  def file_size=(value); end
  def file_unique_id; end
  def file_unique_id=(value); end
  def length; end
  def length=(value); end
  def thumb; end
  def thumb=(value); end
end
class Telegram::Bot::Types::VideoNote < Telegram::Bot::Types::Base
  include Anonymous_Virtus_AttributeSet_114
end
module Anonymous_Virtus_AttributeSet_115
  def first_name; end
  def first_name=(value); end
  def last_name; end
  def last_name=(value); end
  def phone_number; end
  def phone_number=(value); end
  def user_id; end
  def user_id=(value); end
  def vcard; end
  def vcard=(value); end
end
class Telegram::Bot::Types::Contact < Telegram::Bot::Types::Base
  include Anonymous_Virtus_AttributeSet_115
end
module Anonymous_Virtus_AttributeSet_116
  def emoji; end
  def emoji=(value); end
  def value; end
  def value=(value); end
end
class Telegram::Bot::Types::Dice < Telegram::Bot::Types::Base
  include Anonymous_Virtus_AttributeSet_116
end
module Anonymous_Virtus_AttributeSet_117
  def latitude; end
  def latitude=(value); end
  def longitude; end
  def longitude=(value); end
end
class Telegram::Bot::Types::Location < Telegram::Bot::Types::Base
  include Anonymous_Virtus_AttributeSet_117
end
module Anonymous_Virtus_AttributeSet_118
  def big_file_id; end
  def big_file_id=(value); end
  def big_file_unique_id; end
  def big_file_unique_id=(value); end
  def small_file_id; end
  def small_file_id=(value); end
  def small_file_unique_id; end
  def small_file_unique_id=(value); end
end
class Telegram::Bot::Types::ChatPhoto < Telegram::Bot::Types::Base
  include Anonymous_Virtus_AttributeSet_118
end
module Anonymous_Virtus_AttributeSet_119
  def can_add_web_page_previews; end
  def can_add_web_page_previews=(value); end
  def can_add_web_page_previews?; end
  def can_change_info; end
  def can_change_info=(value); end
  def can_change_info?; end
  def can_invite_users; end
  def can_invite_users=(value); end
  def can_invite_users?; end
  def can_pin_messages; end
  def can_pin_messages=(value); end
  def can_pin_messages?; end
  def can_send_media_messages; end
  def can_send_media_messages=(value); end
  def can_send_media_messages?; end
  def can_send_messages; end
  def can_send_messages=(value); end
  def can_send_messages?; end
  def can_send_other_messages; end
  def can_send_other_messages=(value); end
  def can_send_other_messages?; end
  def can_send_polls; end
  def can_send_polls=(value); end
  def can_send_polls?; end
end
class Telegram::Bot::Types::ChatPermissions < Telegram::Bot::Types::Base
  include Anonymous_Virtus_AttributeSet_119
end
class Telegram::Bot::Types::Chat
  def self.attribute(name, type = nil, options = nil); end
  extend Virtus::ClassMethods
  extend Virtus::Extensions::AllowedWriterMethods
  include Anonymous_Module_121
  include Anonymous_Virtus_AttributeSet_120
  include Telegram::Bot::Types::Compactable
  include Virtus::ClassInclusions::Methods
  include Virtus::InstanceMethods
  include Virtus::InstanceMethods::Constructor
  include Virtus::InstanceMethods::MassAssignment
  include Virtus::Model::Constructor
  include Virtus::Model::Core
  include Virtus::Model::MassAssignment
end
module Anonymous_Module_121
  def self.extended(object); end
  def self.included(object); end
end
module Anonymous_Virtus_AttributeSet_120
  def all_members_are_administrators; end
  def all_members_are_administrators=(value); end
  def all_members_are_administrators?; end
  def can_set_sticker_set; end
  def can_set_sticker_set=(value); end
  def can_set_sticker_set?; end
  def description; end
  def description=(value); end
  def first_name; end
  def first_name=(value); end
  def id; end
  def id=(value); end
  def invite_link; end
  def invite_link=(value); end
  def last_name; end
  def last_name=(value); end
  def permissions; end
  def permissions=(value); end
  def photo; end
  def photo=(value); end
  def pinned_message; end
  def pinned_message=(value); end
  def slow_mode_delay; end
  def slow_mode_delay=(value); end
  def sticker_set_name; end
  def sticker_set_name=(value); end
  def title; end
  def title=(value); end
  def type; end
  def type=(value); end
  def username; end
  def username=(value); end
end
module Anonymous_Virtus_AttributeSet_122
  def language; end
  def language=(value); end
  def length; end
  def length=(value); end
  def offset; end
  def offset=(value); end
  def type; end
  def type=(value); end
  def url; end
  def url=(value); end
  def user; end
  def user=(value); end
end
class Telegram::Bot::Types::MessageEntity < Telegram::Bot::Types::Base
  include Anonymous_Virtus_AttributeSet_122
end
module Anonymous_Virtus_AttributeSet_123
  def address; end
  def address=(value); end
  def foursquare_id; end
  def foursquare_id=(value); end
  def foursquare_type; end
  def foursquare_type=(value); end
  def location; end
  def location=(value); end
  def title; end
  def title=(value); end
end
class Telegram::Bot::Types::Venue < Telegram::Bot::Types::Base
  include Anonymous_Virtus_AttributeSet_123
end
module Anonymous_Virtus_AttributeSet_124
  def duration; end
  def duration=(value); end
  def file_id; end
  def file_id=(value); end
  def file_name; end
  def file_name=(value); end
  def file_size; end
  def file_size=(value); end
  def file_unique_id; end
  def file_unique_id=(value); end
  def height; end
  def height=(value); end
  def mime_type; end
  def mime_type=(value); end
  def thumb; end
  def thumb=(value); end
  def width; end
  def width=(value); end
end
class Telegram::Bot::Types::Animation < Telegram::Bot::Types::Base
  include Anonymous_Virtus_AttributeSet_124
end
module Anonymous_Virtus_AttributeSet_125
  def animation; end
  def animation=(value); end
  def description; end
  def description=(value); end
  def photo; end
  def photo=(value); end
  def text; end
  def text=(value); end
  def text_entities; end
  def text_entities=(value); end
  def title; end
  def title=(value); end
end
class Telegram::Bot::Types::Game < Telegram::Bot::Types::Base
  include Anonymous_Virtus_AttributeSet_125
end
module Anonymous_Virtus_AttributeSet_126
end
class Telegram::Bot::Types::CallbackGame < Telegram::Bot::Types::Base
  include Anonymous_Virtus_AttributeSet_126
end
module Anonymous_Virtus_AttributeSet_127
  def position; end
  def position=(value); end
  def score; end
  def score=(value); end
  def user; end
  def user=(value); end
end
class Telegram::Bot::Types::GameHighScore < Telegram::Bot::Types::Base
  include Anonymous_Virtus_AttributeSet_127
end
module Anonymous_Virtus_AttributeSet_128
  def currency; end
  def currency=(value); end
  def description; end
  def description=(value); end
  def start_parameter; end
  def start_parameter=(value); end
  def title; end
  def title=(value); end
  def total_amount; end
  def total_amount=(value); end
end
class Telegram::Bot::Types::Invoice < Telegram::Bot::Types::Base
  include Anonymous_Virtus_AttributeSet_128
end
module Anonymous_Virtus_AttributeSet_129
  def city; end
  def city=(value); end
  def country_code; end
  def country_code=(value); end
  def post_code; end
  def post_code=(value); end
  def state; end
  def state=(value); end
  def street_line1; end
  def street_line1=(value); end
  def street_line2; end
  def street_line2=(value); end
end
class Telegram::Bot::Types::ShippingAddress < Telegram::Bot::Types::Base
  include Anonymous_Virtus_AttributeSet_129
end
module Anonymous_Virtus_AttributeSet_130
  def email; end
  def email=(value); end
  def name; end
  def name=(value); end
  def phone_number; end
  def phone_number=(value); end
  def shipping_address; end
  def shipping_address=(value); end
end
class Telegram::Bot::Types::OrderInfo < Telegram::Bot::Types::Base
  include Anonymous_Virtus_AttributeSet_130
end
module Anonymous_Virtus_AttributeSet_131
  def currency; end
  def currency=(value); end
  def invoice_payload; end
  def invoice_payload=(value); end
  def order_info; end
  def order_info=(value); end
  def provider_payment_charge_id; end
  def provider_payment_charge_id=(value); end
  def shipping_option_id; end
  def shipping_option_id=(value); end
  def telegram_payment_charge_id; end
  def telegram_payment_charge_id=(value); end
  def total_amount; end
  def total_amount=(value); end
end
class Telegram::Bot::Types::SuccessfulPayment < Telegram::Bot::Types::Base
  include Anonymous_Virtus_AttributeSet_131
end
module Anonymous_Virtus_AttributeSet_132
  def text; end
  def text=(value); end
  def voter_count; end
  def voter_count=(value); end
end
class Telegram::Bot::Types::PollOption < Telegram::Bot::Types::Base
  include Anonymous_Virtus_AttributeSet_132
end
module Anonymous_Virtus_AttributeSet_133
  def option_ids; end
  def option_ids=(value); end
  def poll_id; end
  def poll_id=(value); end
  def user; end
  def user=(value); end
end
class Telegram::Bot::Types::PollAnswer < Telegram::Bot::Types::Base
  include Anonymous_Virtus_AttributeSet_133
end
module Anonymous_Virtus_AttributeSet_134
  def allows_multiple_answers; end
  def allows_multiple_answers=(value); end
  def allows_multiple_answers?; end
  def close_date; end
  def close_date=(value); end
  def correct_option_id; end
  def correct_option_id=(value); end
  def explanation; end
  def explanation=(value); end
  def explanation_entities; end
  def explanation_entities=(value); end
  def id; end
  def id=(value); end
  def is_anonymous; end
  def is_anonymous=(value); end
  def is_anonymous?; end
  def is_closed; end
  def is_closed=(value); end
  def is_closed?; end
  def open_period; end
  def open_period=(value); end
  def options; end
  def options=(value); end
  def question; end
  def question=(value); end
  def total_voter_count; end
  def total_voter_count=(value); end
  def type; end
  def type=(value); end
end
class Telegram::Bot::Types::Poll < Telegram::Bot::Types::Base
  include Anonymous_Virtus_AttributeSet_134
end
module Anonymous_Virtus_AttributeSet_135
  def file_date; end
  def file_date=(value); end
  def file_id; end
  def file_id=(value); end
  def file_size; end
  def file_size=(value); end
  def file_unique_id; end
  def file_unique_id=(value); end
end
class Telegram::Bot::Types::PassportFile < Telegram::Bot::Types::Base
  include Anonymous_Virtus_AttributeSet_135
end
module Anonymous_Virtus_AttributeSet_136
  def data; end
  def data=(value); end
  def email; end
  def email=(value); end
  def files; end
  def files=(value); end
  def front_side; end
  def front_side=(value); end
  def hash; end
  def hash=(value); end
  def phone_number; end
  def phone_number=(value); end
  def reverse_side; end
  def reverse_side=(value); end
  def selfie; end
  def selfie=(value); end
  def translation; end
  def translation=(value); end
  def type; end
  def type=(value); end
end
class Telegram::Bot::Types::EncryptedPassportElement < Telegram::Bot::Types::Base
  include Anonymous_Virtus_AttributeSet_136
end
module Anonymous_Virtus_AttributeSet_137
  def data; end
  def data=(value); end
  def hash; end
  def hash=(value); end
  def secret; end
  def secret=(value); end
end
class Telegram::Bot::Types::EncryptedCredentials < Telegram::Bot::Types::Base
  include Anonymous_Virtus_AttributeSet_137
end
module Anonymous_Virtus_AttributeSet_138
  def credentials; end
  def credentials=(value); end
  def data; end
  def data=(value); end
end
class Telegram::Bot::Types::PassportData < Telegram::Bot::Types::Base
  include Anonymous_Virtus_AttributeSet_138
end
module Anonymous_Virtus_AttributeSet_139
  def data_hash; end
  def data_hash=(value); end
  def field_name; end
  def field_name=(value); end
  def message; end
  def message=(value); end
  def source; end
  def source=(value); end
  def type; end
  def type=(value); end
end
class Telegram::Bot::Types::PassportElementErrorDataField < Telegram::Bot::Types::Base
  include Anonymous_Virtus_AttributeSet_139
end
module Anonymous_Virtus_AttributeSet_140
  def file_hash; end
  def file_hash=(value); end
  def message; end
  def message=(value); end
  def source; end
  def source=(value); end
  def type; end
  def type=(value); end
end
class Telegram::Bot::Types::PassportElementErrorFrontSide < Telegram::Bot::Types::Base
  include Anonymous_Virtus_AttributeSet_140
end
module Anonymous_Virtus_AttributeSet_141
  def file_hash; end
  def file_hash=(value); end
  def message; end
  def message=(value); end
  def source; end
  def source=(value); end
  def type; end
  def type=(value); end
end
class Telegram::Bot::Types::PassportElementErrorReverseSide < Telegram::Bot::Types::Base
  include Anonymous_Virtus_AttributeSet_141
end
module Anonymous_Virtus_AttributeSet_142
  def file_hash; end
  def file_hash=(value); end
  def message; end
  def message=(value); end
  def source; end
  def source=(value); end
  def type; end
  def type=(value); end
end
class Telegram::Bot::Types::PassportElementErrorSelfie < Telegram::Bot::Types::Base
  include Anonymous_Virtus_AttributeSet_142
end
module Anonymous_Virtus_AttributeSet_143
  def file_hash; end
  def file_hash=(value); end
  def message; end
  def message=(value); end
  def source; end
  def source=(value); end
  def type; end
  def type=(value); end
end
class Telegram::Bot::Types::PassportElementErrorFile < Telegram::Bot::Types::Base
  include Anonymous_Virtus_AttributeSet_143
end
module Anonymous_Virtus_AttributeSet_144
  def file_hashes; end
  def file_hashes=(value); end
  def message; end
  def message=(value); end
  def source; end
  def source=(value); end
  def type; end
  def type=(value); end
end
class Telegram::Bot::Types::PassportElementErrorFiles < Telegram::Bot::Types::Base
  include Anonymous_Virtus_AttributeSet_144
end
module Anonymous_Virtus_AttributeSet_145
  def file_hash; end
  def file_hash=(value); end
  def message; end
  def message=(value); end
  def source; end
  def source=(value); end
  def type; end
  def type=(value); end
end
class Telegram::Bot::Types::PassportElementErrorTranslationFile < Telegram::Bot::Types::Base
  include Anonymous_Virtus_AttributeSet_145
end
module Anonymous_Virtus_AttributeSet_146
  def file_hashes; end
  def file_hashes=(value); end
  def message; end
  def message=(value); end
  def source; end
  def source=(value); end
  def type; end
  def type=(value); end
end
class Telegram::Bot::Types::PassportElementErrorTranslationFiles < Telegram::Bot::Types::Base
  include Anonymous_Virtus_AttributeSet_146
end
module Anonymous_Virtus_AttributeSet_147
  def element_hash; end
  def element_hash=(value); end
  def message; end
  def message=(value); end
  def source; end
  def source=(value); end
  def type; end
  def type=(value); end
end
class Telegram::Bot::Types::PassportElementErrorUnspecified < Telegram::Bot::Types::Base
  include Anonymous_Virtus_AttributeSet_147
end
module Anonymous_Virtus_AttributeSet_148
end
class Telegram::Bot::Types::InputMessageContent < Telegram::Bot::Types::Base
  include Anonymous_Virtus_AttributeSet_148
end
module Anonymous_Virtus_AttributeSet_149
  def first_name; end
  def first_name=(value); end
  def last_name; end
  def last_name=(value); end
  def phone_number; end
  def phone_number=(value); end
  def vcard; end
  def vcard=(value); end
end
class Telegram::Bot::Types::InputContactMessageContent < Telegram::Bot::Types::InputMessageContent
  include Anonymous_Virtus_AttributeSet_149
end
module Anonymous_Virtus_AttributeSet_150
  def latitude; end
  def latitude=(value); end
  def longitude; end
  def longitude=(value); end
end
class Telegram::Bot::Types::InputLocationMessageContent < Telegram::Bot::Types::InputMessageContent
  include Anonymous_Virtus_AttributeSet_150
end
module Anonymous_Virtus_AttributeSet_151
  def disable_web_page_preview; end
  def disable_web_page_preview=(value); end
  def disable_web_page_preview?; end
  def message_text; end
  def message_text=(value); end
  def parse_mode; end
  def parse_mode=(value); end
end
class Telegram::Bot::Types::InputTextMessageContent < Telegram::Bot::Types::InputMessageContent
  include Anonymous_Virtus_AttributeSet_151
end
module Anonymous_Virtus_AttributeSet_152
  def address; end
  def address=(value); end
  def foursquare_id; end
  def foursquare_id=(value); end
  def foursquare_type; end
  def foursquare_type=(value); end
  def latitude; end
  def latitude=(value); end
  def longitude; end
  def longitude=(value); end
  def title; end
  def title=(value); end
end
class Telegram::Bot::Types::InputVenueMessageContent < Telegram::Bot::Types::InputMessageContent
  include Anonymous_Virtus_AttributeSet_152
end
module Anonymous_Virtus_AttributeSet_153
  def bot_username; end
  def bot_username=(value); end
  def forward_text; end
  def forward_text=(value); end
  def request_write_access; end
  def request_write_access=(value); end
  def request_write_access?; end
  def url; end
  def url=(value); end
end
class Telegram::Bot::Types::LoginUrl < Telegram::Bot::Types::Base
  include Anonymous_Virtus_AttributeSet_153
end
module Anonymous_Virtus_AttributeSet_154
  def callback_data; end
  def callback_data=(value); end
  def callback_game; end
  def callback_game=(value); end
  def login_url; end
  def login_url=(value); end
  def pay; end
  def pay=(value); end
  def pay?; end
  def switch_inline_query; end
  def switch_inline_query=(value); end
  def switch_inline_query_current_chat; end
  def switch_inline_query_current_chat=(value); end
  def text; end
  def text=(value); end
  def url; end
  def url=(value); end
end
class Telegram::Bot::Types::InlineKeyboardButton < Telegram::Bot::Types::Base
  include Anonymous_Virtus_AttributeSet_154
end
module Anonymous_Virtus_AttributeSet_155
  def inline_keyboard; end
  def inline_keyboard=(value); end
end
class Telegram::Bot::Types::InlineKeyboardMarkup < Telegram::Bot::Types::Base
  def to_compact_hash; end
  include Anonymous_Virtus_AttributeSet_155
end
module Anonymous_Virtus_AttributeSet_156
  def from; end
  def from=(value); end
  def id; end
  def id=(value); end
  def location; end
  def location=(value); end
  def offset; end
  def offset=(value); end
  def query; end
  def query=(value); end
end
class Telegram::Bot::Types::InlineQuery < Telegram::Bot::Types::Base
  def to_s; end
  include Anonymous_Virtus_AttributeSet_156
end
module Anonymous_Virtus_AttributeSet_157
  def description; end
  def description=(value); end
  def hide_url; end
  def hide_url=(value); end
  def hide_url?; end
  def id; end
  def id=(value); end
  def input_message_content; end
  def input_message_content=(value); end
  def reply_markup; end
  def reply_markup=(value); end
  def thumb_height; end
  def thumb_height=(value); end
  def thumb_url; end
  def thumb_url=(value); end
  def thumb_width; end
  def thumb_width=(value); end
  def title; end
  def title=(value); end
  def type; end
  def type=(value); end
  def url; end
  def url=(value); end
end
class Telegram::Bot::Types::InlineQueryResultArticle < Telegram::Bot::Types::Base
  include Anonymous_Virtus_AttributeSet_157
end
module Anonymous_Virtus_AttributeSet_158
  def audio_duration; end
  def audio_duration=(value); end
  def audio_url; end
  def audio_url=(value); end
  def caption; end
  def caption=(value); end
  def id; end
  def id=(value); end
  def input_message_content; end
  def input_message_content=(value); end
  def performer; end
  def performer=(value); end
  def reply_markup; end
  def reply_markup=(value); end
  def title; end
  def title=(value); end
  def type; end
  def type=(value); end
end
class Telegram::Bot::Types::InlineQueryResultAudio < Telegram::Bot::Types::Base
  include Anonymous_Virtus_AttributeSet_158
end
module Anonymous_Virtus_AttributeSet_159
  def audio_file_id; end
  def audio_file_id=(value); end
  def caption; end
  def caption=(value); end
  def id; end
  def id=(value); end
  def input_message_content; end
  def input_message_content=(value); end
  def reply_markup; end
  def reply_markup=(value); end
  def type; end
  def type=(value); end
end
class Telegram::Bot::Types::InlineQueryResultCachedAudio < Telegram::Bot::Types::Base
  include Anonymous_Virtus_AttributeSet_159
end
module Anonymous_Virtus_AttributeSet_160
  def caption; end
  def caption=(value); end
  def description; end
  def description=(value); end
  def document_file_id; end
  def document_file_id=(value); end
  def id; end
  def id=(value); end
  def input_message_content; end
  def input_message_content=(value); end
  def reply_markup; end
  def reply_markup=(value); end
  def title; end
  def title=(value); end
  def type; end
  def type=(value); end
end
class Telegram::Bot::Types::InlineQueryResultCachedDocument < Telegram::Bot::Types::Base
  include Anonymous_Virtus_AttributeSet_160
end
module Anonymous_Virtus_AttributeSet_161
  def caption; end
  def caption=(value); end
  def gif_file_id; end
  def gif_file_id=(value); end
  def id; end
  def id=(value); end
  def input_message_content; end
  def input_message_content=(value); end
  def reply_markup; end
  def reply_markup=(value); end
  def title; end
  def title=(value); end
  def type; end
  def type=(value); end
end
class Telegram::Bot::Types::InlineQueryResultCachedGif < Telegram::Bot::Types::Base
  include Anonymous_Virtus_AttributeSet_161
end
module Anonymous_Virtus_AttributeSet_162
  def caption; end
  def caption=(value); end
  def id; end
  def id=(value); end
  def input_message_content; end
  def input_message_content=(value); end
  def mpeg4_file_id; end
  def mpeg4_file_id=(value); end
  def reply_markup; end
  def reply_markup=(value); end
  def title; end
  def title=(value); end
  def type; end
  def type=(value); end
end
class Telegram::Bot::Types::InlineQueryResultCachedMpeg4Gif < Telegram::Bot::Types::Base
  include Anonymous_Virtus_AttributeSet_162
end
module Anonymous_Virtus_AttributeSet_163
  def caption; end
  def caption=(value); end
  def description; end
  def description=(value); end
  def id; end
  def id=(value); end
  def input_message_content; end
  def input_message_content=(value); end
  def photo_file_id; end
  def photo_file_id=(value); end
  def reply_markup; end
  def reply_markup=(value); end
  def title; end
  def title=(value); end
  def type; end
  def type=(value); end
end
class Telegram::Bot::Types::InlineQueryResultCachedPhoto < Telegram::Bot::Types::Base
  include Anonymous_Virtus_AttributeSet_163
end
module Anonymous_Virtus_AttributeSet_164
  def id; end
  def id=(value); end
  def input_message_content; end
  def input_message_content=(value); end
  def reply_markup; end
  def reply_markup=(value); end
  def sticker_file_id; end
  def sticker_file_id=(value); end
  def type; end
  def type=(value); end
end
class Telegram::Bot::Types::InlineQueryResultCachedSticker < Telegram::Bot::Types::Base
  include Anonymous_Virtus_AttributeSet_164
end
module Anonymous_Virtus_AttributeSet_165
  def caption; end
  def caption=(value); end
  def description; end
  def description=(value); end
  def id; end
  def id=(value); end
  def input_message_content; end
  def input_message_content=(value); end
  def reply_markup; end
  def reply_markup=(value); end
  def title; end
  def title=(value); end
  def type; end
  def type=(value); end
  def video_file_id; end
  def video_file_id=(value); end
end
class Telegram::Bot::Types::InlineQueryResultCachedVideo < Telegram::Bot::Types::Base
  include Anonymous_Virtus_AttributeSet_165
end
module Anonymous_Virtus_AttributeSet_166
  def caption; end
  def caption=(value); end
  def id; end
  def id=(value); end
  def input_message_content; end
  def input_message_content=(value); end
  def reply_markup; end
  def reply_markup=(value); end
  def title; end
  def title=(value); end
  def type; end
  def type=(value); end
  def voice_file_id; end
  def voice_file_id=(value); end
end
class Telegram::Bot::Types::InlineQueryResultCachedVoice < Telegram::Bot::Types::Base
  include Anonymous_Virtus_AttributeSet_166
end
module Anonymous_Virtus_AttributeSet_167
  def first_name; end
  def first_name=(value); end
  def id; end
  def id=(value); end
  def input_message_content; end
  def input_message_content=(value); end
  def last_name; end
  def last_name=(value); end
  def phone_number; end
  def phone_number=(value); end
  def reply_markup; end
  def reply_markup=(value); end
  def thumb_height; end
  def thumb_height=(value); end
  def thumb_url; end
  def thumb_url=(value); end
  def thumb_width; end
  def thumb_width=(value); end
  def type; end
  def type=(value); end
  def vcard; end
  def vcard=(value); end
end
class Telegram::Bot::Types::InlineQueryResultContact < Telegram::Bot::Types::Base
  include Anonymous_Virtus_AttributeSet_167
end
module Anonymous_Virtus_AttributeSet_168
  def game_short_name; end
  def game_short_name=(value); end
  def id; end
  def id=(value); end
  def reply_markup; end
  def reply_markup=(value); end
  def type; end
  def type=(value); end
end
class Telegram::Bot::Types::InlineQueryResultGame < Telegram::Bot::Types::Base
  include Anonymous_Virtus_AttributeSet_168
end
module Anonymous_Virtus_AttributeSet_169
  def caption; end
  def caption=(value); end
  def description; end
  def description=(value); end
  def document_url; end
  def document_url=(value); end
  def id; end
  def id=(value); end
  def input_message_content; end
  def input_message_content=(value); end
  def mime_type; end
  def mime_type=(value); end
  def reply_markup; end
  def reply_markup=(value); end
  def thumb_height; end
  def thumb_height=(value); end
  def thumb_url; end
  def thumb_url=(value); end
  def thumb_width; end
  def thumb_width=(value); end
  def title; end
  def title=(value); end
  def type; end
  def type=(value); end
end
class Telegram::Bot::Types::InlineQueryResultDocument < Telegram::Bot::Types::Base
  include Anonymous_Virtus_AttributeSet_169
end
module Anonymous_Virtus_AttributeSet_170
  def caption; end
  def caption=(value); end
  def gif_duration; end
  def gif_duration=(value); end
  def gif_height; end
  def gif_height=(value); end
  def gif_url; end
  def gif_url=(value); end
  def gif_width; end
  def gif_width=(value); end
  def id; end
  def id=(value); end
  def input_message_content; end
  def input_message_content=(value); end
  def reply_markup; end
  def reply_markup=(value); end
  def thumb_mime_type; end
  def thumb_mime_type=(value); end
  def thumb_url; end
  def thumb_url=(value); end
  def title; end
  def title=(value); end
  def type; end
  def type=(value); end
end
class Telegram::Bot::Types::InlineQueryResultGif < Telegram::Bot::Types::Base
  include Anonymous_Virtus_AttributeSet_170
end
module Anonymous_Virtus_AttributeSet_171
  def id; end
  def id=(value); end
  def input_message_content; end
  def input_message_content=(value); end
  def latitude; end
  def latitude=(value); end
  def longitude; end
  def longitude=(value); end
  def reply_markup; end
  def reply_markup=(value); end
  def thumb_height; end
  def thumb_height=(value); end
  def thumb_url; end
  def thumb_url=(value); end
  def thumb_width; end
  def thumb_width=(value); end
  def title; end
  def title=(value); end
  def type; end
  def type=(value); end
end
class Telegram::Bot::Types::InlineQueryResultLocation < Telegram::Bot::Types::Base
  include Anonymous_Virtus_AttributeSet_171
end
module Anonymous_Virtus_AttributeSet_172
  def caption; end
  def caption=(value); end
  def id; end
  def id=(value); end
  def input_message_content; end
  def input_message_content=(value); end
  def mpeg4_duration; end
  def mpeg4_duration=(value); end
  def mpeg4_height; end
  def mpeg4_height=(value); end
  def mpeg4_url; end
  def mpeg4_url=(value); end
  def mpeg4_width; end
  def mpeg4_width=(value); end
  def reply_markup; end
  def reply_markup=(value); end
  def thumb_mime_type; end
  def thumb_mime_type=(value); end
  def thumb_url; end
  def thumb_url=(value); end
  def title; end
  def title=(value); end
  def type; end
  def type=(value); end
end
class Telegram::Bot::Types::InlineQueryResultMpeg4Gif < Telegram::Bot::Types::Base
  include Anonymous_Virtus_AttributeSet_172
end
module Anonymous_Virtus_AttributeSet_173
  def caption; end
  def caption=(value); end
  def description; end
  def description=(value); end
  def id; end
  def id=(value); end
  def input_message_content; end
  def input_message_content=(value); end
  def photo_height; end
  def photo_height=(value); end
  def photo_url; end
  def photo_url=(value); end
  def photo_width; end
  def photo_width=(value); end
  def reply_markup; end
  def reply_markup=(value); end
  def thumb_url; end
  def thumb_url=(value); end
  def title; end
  def title=(value); end
  def type; end
  def type=(value); end
end
class Telegram::Bot::Types::InlineQueryResultPhoto < Telegram::Bot::Types::Base
  include Anonymous_Virtus_AttributeSet_173
end
module Anonymous_Virtus_AttributeSet_174
  def address; end
  def address=(value); end
  def foursquare_id; end
  def foursquare_id=(value); end
  def foursquare_type; end
  def foursquare_type=(value); end
  def id; end
  def id=(value); end
  def input_message_content; end
  def input_message_content=(value); end
  def latitude; end
  def latitude=(value); end
  def longitude; end
  def longitude=(value); end
  def reply_markup; end
  def reply_markup=(value); end
  def thumb_height; end
  def thumb_height=(value); end
  def thumb_url; end
  def thumb_url=(value); end
  def thumb_width; end
  def thumb_width=(value); end
  def title; end
  def title=(value); end
  def type; end
  def type=(value); end
end
class Telegram::Bot::Types::InlineQueryResultVenue < Telegram::Bot::Types::Base
  include Anonymous_Virtus_AttributeSet_174
end
module Anonymous_Virtus_AttributeSet_175
  def caption; end
  def caption=(value); end
  def description; end
  def description=(value); end
  def id; end
  def id=(value); end
  def input_message_content; end
  def input_message_content=(value); end
  def mime_type; end
  def mime_type=(value); end
  def reply_markup; end
  def reply_markup=(value); end
  def thumb_url; end
  def thumb_url=(value); end
  def title; end
  def title=(value); end
  def type; end
  def type=(value); end
  def video_duration; end
  def video_duration=(value); end
  def video_height; end
  def video_height=(value); end
  def video_url; end
  def video_url=(value); end
  def video_width; end
  def video_width=(value); end
end
class Telegram::Bot::Types::InlineQueryResultVideo < Telegram::Bot::Types::Base
  include Anonymous_Virtus_AttributeSet_175
end
module Anonymous_Virtus_AttributeSet_176
  def caption; end
  def caption=(value); end
  def id; end
  def id=(value); end
  def input_message_content; end
  def input_message_content=(value); end
  def reply_markup; end
  def reply_markup=(value); end
  def title; end
  def title=(value); end
  def type; end
  def type=(value); end
  def voice_duration; end
  def voice_duration=(value); end
  def voice_url; end
  def voice_url=(value); end
end
class Telegram::Bot::Types::InlineQueryResultVoice < Telegram::Bot::Types::Base
  include Anonymous_Virtus_AttributeSet_176
end
module Anonymous_Virtus_AttributeSet_177
  def from; end
  def from=(value); end
  def inline_message_id; end
  def inline_message_id=(value); end
  def location; end
  def location=(value); end
  def query; end
  def query=(value); end
  def result_id; end
  def result_id=(value); end
end
class Telegram::Bot::Types::ChosenInlineResult < Telegram::Bot::Types::Base
  def to_s; end
  include Anonymous_Virtus_AttributeSet_177
end
module Anonymous_Virtus_AttributeSet_178
  def animation; end
  def animation=(value); end
  def audio; end
  def audio=(value); end
  def author_signature; end
  def author_signature=(value); end
  def caption; end
  def caption=(value); end
  def caption_entities; end
  def caption_entities=(value); end
  def channel_chat_created; end
  def channel_chat_created=(value); end
  def channel_chat_created?; end
  def chat; end
  def chat=(value); end
  def connected_website; end
  def connected_website=(value); end
  def contact; end
  def contact=(value); end
  def date; end
  def date=(value); end
  def delete_chat_photo; end
  def delete_chat_photo=(value); end
  def delete_chat_photo?; end
  def dice; end
  def dice=(value); end
  def document; end
  def document=(value); end
  def edit_date; end
  def edit_date=(value); end
  def entities; end
  def entities=(value); end
  def forward_date; end
  def forward_date=(value); end
  def forward_from; end
  def forward_from=(value); end
  def forward_from_chat; end
  def forward_from_chat=(value); end
  def forward_from_message_id; end
  def forward_from_message_id=(value); end
  def forward_sender_name; end
  def forward_sender_name=(value); end
  def forward_signature; end
  def forward_signature=(value); end
  def from; end
  def from=(value); end
  def game; end
  def game=(value); end
  def group_chat_created; end
  def group_chat_created=(value); end
  def group_chat_created?; end
  def invoice; end
  def invoice=(value); end
  def left_chat_member; end
  def left_chat_member=(value); end
  def location; end
  def location=(value); end
  def media_group_id; end
  def media_group_id=(value); end
  def message_id; end
  def message_id=(value); end
  def migrate_from_chat_id; end
  def migrate_from_chat_id=(value); end
  def migrate_to_chat_id; end
  def migrate_to_chat_id=(value); end
  def new_chat_members; end
  def new_chat_members=(value); end
  def new_chat_photo; end
  def new_chat_photo=(value); end
  def new_chat_title; end
  def new_chat_title=(value); end
  def passport_data; end
  def passport_data=(value); end
  def photo; end
  def photo=(value); end
  def pinned_message; end
  def pinned_message=(value); end
  def poll; end
  def poll=(value); end
  def reply_markup; end
  def reply_markup=(value); end
  def reply_to_message; end
  def reply_to_message=(value); end
  def sticker; end
  def sticker=(value); end
  def successful_payment; end
  def successful_payment=(value); end
  def supergroup_chat_created; end
  def supergroup_chat_created=(value); end
  def supergroup_chat_created?; end
  def text; end
  def text=(value); end
  def venue; end
  def venue=(value); end
  def via_bot; end
  def via_bot=(value); end
  def video; end
  def video=(value); end
  def video_note; end
  def video_note=(value); end
  def voice; end
  def voice=(value); end
end
class Telegram::Bot::Types::Message < Telegram::Bot::Types::Base
  def to_s; end
  include Anonymous_Virtus_AttributeSet_178
end
module Anonymous_Virtus_AttributeSet_179
  def chat_instance; end
  def chat_instance=(value); end
  def data; end
  def data=(value); end
  def from; end
  def from=(value); end
  def game_short_name; end
  def game_short_name=(value); end
  def id; end
  def id=(value); end
  def inline_message_id; end
  def inline_message_id=(value); end
  def message; end
  def message=(value); end
end
class Telegram::Bot::Types::CallbackQuery < Telegram::Bot::Types::Base
  include Anonymous_Virtus_AttributeSet_179
end
module Anonymous_Virtus_AttributeSet_180
  def from; end
  def from=(value); end
  def id; end
  def id=(value); end
  def invoice_payload; end
  def invoice_payload=(value); end
  def shipping_address; end
  def shipping_address=(value); end
end
class Telegram::Bot::Types::ShippingQuery < Telegram::Bot::Types::Base
  include Anonymous_Virtus_AttributeSet_180
end
module Anonymous_Virtus_AttributeSet_181
  def currency; end
  def currency=(value); end
  def from; end
  def from=(value); end
  def id; end
  def id=(value); end
  def invoice_payload; end
  def invoice_payload=(value); end
  def order_info; end
  def order_info=(value); end
  def shipping_option_id; end
  def shipping_option_id=(value); end
  def total_amount; end
  def total_amount=(value); end
end
class Telegram::Bot::Types::PreCheckoutQuery < Telegram::Bot::Types::Base
  include Anonymous_Virtus_AttributeSet_181
end
module Anonymous_Virtus_AttributeSet_182
  def callback_query; end
  def callback_query=(value); end
  def channel_post; end
  def channel_post=(value); end
  def chosen_inline_result; end
  def chosen_inline_result=(value); end
  def edited_channel_post; end
  def edited_channel_post=(value); end
  def edited_message; end
  def edited_message=(value); end
  def inline_query; end
  def inline_query=(value); end
  def message; end
  def message=(value); end
  def poll; end
  def poll=(value); end
  def poll_answer; end
  def poll_answer=(value); end
  def pre_checkout_query; end
  def pre_checkout_query=(value); end
  def shipping_query; end
  def shipping_query=(value); end
  def update_id; end
  def update_id=(value); end
end
class Telegram::Bot::Types::Update < Telegram::Bot::Types::Base
  def current_message; end
  include Anonymous_Virtus_AttributeSet_182
end
module Anonymous_Virtus_AttributeSet_183
  def type; end
  def type=(value); end
end
class Telegram::Bot::Types::KeyboardButtonPollType < Telegram::Bot::Types::Base
  include Anonymous_Virtus_AttributeSet_183
end
module Anonymous_Virtus_AttributeSet_184
  def request_contact; end
  def request_contact=(value); end
  def request_contact?; end
  def request_location; end
  def request_location=(value); end
  def request_location?; end
  def request_poll; end
  def request_poll=(value); end
  def text; end
  def text=(value); end
end
class Telegram::Bot::Types::KeyboardButton < Telegram::Bot::Types::Base
  include Anonymous_Virtus_AttributeSet_184
end
module Anonymous_Virtus_AttributeSet_185
  def keyboard; end
  def keyboard=(value); end
  def one_time_keyboard; end
  def one_time_keyboard=(value); end
  def one_time_keyboard?; end
  def resize_keyboard; end
  def resize_keyboard=(value); end
  def resize_keyboard?; end
  def selective; end
  def selective=(value); end
  def selective?; end
end
class Telegram::Bot::Types::ReplyKeyboardMarkup < Telegram::Bot::Types::Base
  def to_compact_hash; end
  include Anonymous_Virtus_AttributeSet_185
end
module Anonymous_Virtus_AttributeSet_186
  def remove_keyboard; end
  def remove_keyboard=(value); end
  def remove_keyboard?; end
  def selective; end
  def selective=(value); end
  def selective?; end
end
class Telegram::Bot::Types::ReplyKeyboardRemove < Telegram::Bot::Types::Base
  include Anonymous_Virtus_AttributeSet_186
end
module Anonymous_Virtus_AttributeSet_187
  def force_reply; end
  def force_reply=(value); end
  def force_reply?; end
  def selective; end
  def selective=(value); end
  def selective?; end
end
class Telegram::Bot::Types::ForceReply < Telegram::Bot::Types::Base
  include Anonymous_Virtus_AttributeSet_187
end
module Anonymous_Virtus_AttributeSet_188
  def file_id; end
  def file_id=(value); end
  def file_path; end
  def file_path=(value); end
  def file_size; end
  def file_size=(value); end
  def file_unique_id; end
  def file_unique_id=(value); end
end
class Telegram::Bot::Types::File < Telegram::Bot::Types::Base
  include Anonymous_Virtus_AttributeSet_188
end
module Anonymous_Virtus_AttributeSet_189
  def amount; end
  def amount=(value); end
  def label; end
  def label=(value); end
end
class Telegram::Bot::Types::LabeledPrice < Telegram::Bot::Types::Base
  include Anonymous_Virtus_AttributeSet_189
end
module Anonymous_Virtus_AttributeSet_190
  def id; end
  def id=(value); end
  def prices; end
  def prices=(value); end
  def title; end
  def title=(value); end
end
class Telegram::Bot::Types::ShippingOption < Telegram::Bot::Types::Base
  include Anonymous_Virtus_AttributeSet_190
end
module Anonymous_Virtus_AttributeSet_191
  def can_add_web_page_previews; end
  def can_add_web_page_previews=(value); end
  def can_add_web_page_previews?; end
  def can_be_edited; end
  def can_be_edited=(value); end
  def can_be_edited?; end
  def can_change_info; end
  def can_change_info=(value); end
  def can_change_info?; end
  def can_delete_messages; end
  def can_delete_messages=(value); end
  def can_delete_messages?; end
  def can_edit_messages; end
  def can_edit_messages=(value); end
  def can_edit_messages?; end
  def can_invite_users; end
  def can_invite_users=(value); end
  def can_invite_users?; end
  def can_pin_messages; end
  def can_pin_messages=(value); end
  def can_pin_messages?; end
  def can_post_messages; end
  def can_post_messages=(value); end
  def can_post_messages?; end
  def can_promote_members; end
  def can_promote_members=(value); end
  def can_promote_members?; end
  def can_restrict_members; end
  def can_restrict_members=(value); end
  def can_restrict_members?; end
  def can_send_media_messages; end
  def can_send_media_messages=(value); end
  def can_send_media_messages?; end
  def can_send_messages; end
  def can_send_messages=(value); end
  def can_send_messages?; end
  def can_send_other_messages; end
  def can_send_other_messages=(value); end
  def can_send_other_messages?; end
  def can_send_polls; end
  def can_send_polls=(value); end
  def can_send_polls?; end
  def custom_title; end
  def custom_title=(value); end
  def is_member; end
  def is_member=(value); end
  def is_member?; end
  def status; end
  def status=(value); end
  def until_date; end
  def until_date=(value); end
  def user; end
  def user=(value); end
end
class Telegram::Bot::Types::ChatMember < Telegram::Bot::Types::Base
  include Anonymous_Virtus_AttributeSet_191
end
module Anonymous_Virtus_AttributeSet_192
  def photos; end
  def photos=(value); end
  def total_count; end
  def total_count=(value); end
end
class Telegram::Bot::Types::UserProfilePhotos < Telegram::Bot::Types::Base
  include Anonymous_Virtus_AttributeSet_192
end
module Anonymous_Virtus_AttributeSet_193
  def caption; end
  def caption=(value); end
  def media; end
  def media=(value); end
  def type; end
  def type=(value); end
end
class Telegram::Bot::Types::InputMediaPhoto < Telegram::Bot::Types::Base
  include Anonymous_Virtus_AttributeSet_193
end
module Anonymous_Virtus_AttributeSet_194
  def caption; end
  def caption=(value); end
  def duration; end
  def duration=(value); end
  def height; end
  def height=(value); end
  def media; end
  def media=(value); end
  def supports_streaming; end
  def supports_streaming=(value); end
  def supports_streaming?; end
  def type; end
  def type=(value); end
  def width; end
  def width=(value); end
end
class Telegram::Bot::Types::InputMediaVideo < Telegram::Bot::Types::Base
  include Anonymous_Virtus_AttributeSet_194
end
module Anonymous_Virtus_AttributeSet_195
  def caption; end
  def caption=(value); end
  def duration; end
  def duration=(value); end
  def height; end
  def height=(value); end
  def media; end
  def media=(value); end
  def parse_mode; end
  def parse_mode=(value); end
  def thumb; end
  def thumb=(value); end
  def type; end
  def type=(value); end
  def width; end
  def width=(value); end
end
class Telegram::Bot::Types::InputMediaAnimation < Telegram::Bot::Types::Base
  include Anonymous_Virtus_AttributeSet_195
end
module Anonymous_Virtus_AttributeSet_196
  def caption; end
  def caption=(value); end
  def duration; end
  def duration=(value); end
  def media; end
  def media=(value); end
  def parse_mode; end
  def parse_mode=(value); end
  def performer; end
  def performer=(value); end
  def thumb; end
  def thumb=(value); end
  def title; end
  def title=(value); end
  def type; end
  def type=(value); end
end
class Telegram::Bot::Types::InputMediaAudio < Telegram::Bot::Types::Base
  include Anonymous_Virtus_AttributeSet_196
end
module Anonymous_Virtus_AttributeSet_197
  def caption; end
  def caption=(value); end
  def media; end
  def media=(value); end
  def parse_mode; end
  def parse_mode=(value); end
  def thumb; end
  def thumb=(value); end
  def type; end
  def type=(value); end
end
class Telegram::Bot::Types::InputMediaDocument < Telegram::Bot::Types::Base
  include Anonymous_Virtus_AttributeSet_197
end
module Telegram::Bot::Exceptions
end
class Telegram::Bot::Exceptions::Base < StandardError
end
class Telegram::Bot::Exceptions::ResponseError < Telegram::Bot::Exceptions::Base
  def data; end
  def error_code; end
  def initialize(response); end
  def response; end
  def to_s; end
end
class Telegram::Bot::Api
  def build_params(h); end
  def call(endpoint, raw_params = nil); end
  def camelize(method_name); end
  def conn; end
  def initialize(token, url: nil); end
  def jsonify_inline_query_results(value); end
  def jsonify_reply_markup(value); end
  def method_missing(method_name, *args, &block); end
  def respond_to_missing?(*args); end
  def sanitize_value(value); end
  def token; end
  def url; end
end
class Telegram::Bot::NullLogger < Logger
  def add(*arg0); end
  def initialize(*arg0); end
end
class Telegram::Bot::Client
  def api; end
  def default_options; end
  def fetch_updates; end
  def initialize(token, hash = nil); end
  def listen(&block); end
  def log_incoming_message(message); end
  def logger; end
  def logger=(arg0); end
  def options; end
  def run; end
  def self.run(*args, &block); end
end
class Telegram::Bot::Configuration
  def adapter; end
  def adapter=(arg0); end
  def initialize; end
end
